/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerDataToTranslate;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerTranslateDataRequest
 */
public class AiproductdataenhancerTranslateDataRequestTest {
    private final AiproductdataenhancerTranslateDataRequest model = new AiproductdataenhancerTranslateDataRequest();

    /**
     * Model tests for AiproductdataenhancerTranslateDataRequest
     */
    @Test
    public void testAiproductdataenhancerTranslateDataRequest() {
        // TODO: test AiproductdataenhancerTranslateDataRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'dataToTranslate'
     */
    @Test
    public void dataToTranslateTest() {
        // TODO: test dataToTranslate
    }

}
