/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.openapitools.client.model.AiproductdataenhancerProductDataToFill;
import org.openapitools.client.model.AiproductdataenhancerProductInformation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerFillProductDataRequest
 */
public class AiproductdataenhancerFillProductDataRequestTest {
    private final AiproductdataenhancerFillProductDataRequest model = new AiproductdataenhancerFillProductDataRequest();

    /**
     * Model tests for AiproductdataenhancerFillProductDataRequest
     */
    @Test
    public void testAiproductdataenhancerFillProductDataRequest() {
        // TODO: test AiproductdataenhancerFillProductDataRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'productInformation'
     */
    @Test
    public void productInformationTest() {
        // TODO: test productInformation
    }

    /**
     * Test the property 'productDataToFill'
     */
    @Test
    public void productDataToFillTest() {
        // TODO: test productDataToFill
    }

    /**
     * Test the property 'domainsToInclude'
     */
    @Test
    public void domainsToIncludeTest() {
        // TODO: test domainsToInclude
    }

    /**
     * Test the property 'domainsToExclude'
     */
    @Test
    public void domainsToExcludeTest() {
        // TODO: test domainsToExclude
    }

}
