/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductInformationImageInfo;
import org.openapitools.client.model.ProductInformationTextInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerGenerateProductDataRequestProductInformation
 */
public class AiproductdataenhancerGenerateProductDataRequestProductInformationTest {
    private final AiproductdataenhancerGenerateProductDataRequestProductInformation model = new AiproductdataenhancerGenerateProductDataRequestProductInformation();

    /**
     * Model tests for AiproductdataenhancerGenerateProductDataRequestProductInformation
     */
    @Test
    public void testAiproductdataenhancerGenerateProductDataRequestProductInformation() {
        // TODO: test AiproductdataenhancerGenerateProductDataRequestProductInformation
    }

    /**
     * Test the property 'textInfo'
     */
    @Test
    public void textInfoTest() {
        // TODO: test textInfo
    }

    /**
     * Test the property 'imageInfo'
     */
    @Test
    public void imageInfoTest() {
        // TODO: test imageInfo
    }

}
