/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerJobStatus
 */
public class AiproductdataenhancerJobStatusTest {
    /**
     * Model tests for AiproductdataenhancerJobStatus
     */
    @Test
    public void testAiproductdataenhancerJobStatus() {
        // TODO: test AiproductdataenhancerJobStatus
    }

}
