/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerTranslateDataResponse
 */
public class AiproductdataenhancerTranslateDataResponseTest {
    private final AiproductdataenhancerTranslateDataResponse model = new AiproductdataenhancerTranslateDataResponse();

    /**
     * Model tests for AiproductdataenhancerTranslateDataResponse
     */
    @Test
    public void testAiproductdataenhancerTranslateDataResponse() {
        // TODO: test AiproductdataenhancerTranslateDataResponse
    }

    /**
     * Test the property 'dataTranslated'
     */
    @Test
    public void dataTranslatedTest() {
        // TODO: test dataTranslated
    }

    /**
     * Test the property 'confidenceRate'
     */
    @Test
    public void confidenceRateTest() {
        // TODO: test confidenceRate
    }

    /**
     * Test the property 'completionRate'
     */
    @Test
    public void completionRateTest() {
        // TODO: test completionRate
    }

}
