/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.AiproductdataenhancerError;
import org.openapitools.client.model.AiproductdataenhancerJobStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerFillProductDataCheckResponse
 */
public class AiproductdataenhancerFillProductDataCheckResponseTest {
    private final AiproductdataenhancerFillProductDataCheckResponse model = new AiproductdataenhancerFillProductDataCheckResponse();

    /**
     * Model tests for AiproductdataenhancerFillProductDataCheckResponse
     */
    @Test
    public void testAiproductdataenhancerFillProductDataCheckResponse() {
        // TODO: test AiproductdataenhancerFillProductDataCheckResponse
    }

    /**
     * Test the property 'productDataFilled'
     */
    @Test
    public void productDataFilledTest() {
        // TODO: test productDataFilled
    }

    /**
     * Test the property 'confidenceRate'
     */
    @Test
    public void confidenceRateTest() {
        // TODO: test confidenceRate
    }

    /**
     * Test the property 'completionRate'
     */
    @Test
    public void completionRateTest() {
        // TODO: test completionRate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
