/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerGenerateProductDataRequestProductInformation;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.openapitools.client.model.GenerateProductDataRequestProductDataToGenerate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiproductdataenhancerGenerateProductDataRequest
 */
public class AiproductdataenhancerGenerateProductDataRequestTest {
    private final AiproductdataenhancerGenerateProductDataRequest model = new AiproductdataenhancerGenerateProductDataRequest();

    /**
     * Model tests for AiproductdataenhancerGenerateProductDataRequest
     */
    @Test
    public void testAiproductdataenhancerGenerateProductDataRequest() {
        // TODO: test AiproductdataenhancerGenerateProductDataRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'productInformation'
     */
    @Test
    public void productInformationTest() {
        // TODO: test productInformation
    }

    /**
     * Test the property 'productDataToGenerate'
     */
    @Test
    public void productDataToGenerateTest() {
        // TODO: test productDataToGenerate
    }

}
