/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.AiproductdataenhancerTone;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GenerateProductDataRequestProductDataToGenerate
 */
public class GenerateProductDataRequestProductDataToGenerateTest {
    private final GenerateProductDataRequestProductDataToGenerate model = new GenerateProductDataRequestProductDataToGenerate();

    /**
     * Model tests for GenerateProductDataRequestProductDataToGenerate
     */
    @Test
    public void testGenerateProductDataRequestProductDataToGenerate() {
        // TODO: test GenerateProductDataRequestProductDataToGenerate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'valueSet'
     */
    @Test
    public void valueSetTest() {
        // TODO: test valueSet
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'tone'
     */
    @Test
    public void toneTest() {
        // TODO: test tone
    }

}
