/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.openapitools.client.model.AiproductdataenhancerProductDataToFill;
import org.openapitools.client.model.AiproductdataenhancerProductInformation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.AiProductDataEnhancer.JSON;

/**
 * AiproductdataenhancerFillProductDataRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-20T14:54:03.495312875Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class AiproductdataenhancerFillProductDataRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_LANGUAGE_CODE = "languageCode";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_CODE)
  private AiproductdataenhancerLanguageCode languageCode = AiproductdataenhancerLanguageCode.UNKNOWN;

  public static final String SERIALIZED_NAME_PRODUCT_INFORMATION = "productInformation";
  @SerializedName(SERIALIZED_NAME_PRODUCT_INFORMATION)
  private AiproductdataenhancerProductInformation productInformation;

  public static final String SERIALIZED_NAME_PRODUCT_DATA_TO_FILL = "productDataToFill";
  @SerializedName(SERIALIZED_NAME_PRODUCT_DATA_TO_FILL)
  private List<AiproductdataenhancerProductDataToFill> productDataToFill = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOMAINS_TO_INCLUDE = "domainsToInclude";
  @SerializedName(SERIALIZED_NAME_DOMAINS_TO_INCLUDE)
  private List<String> domainsToInclude = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOMAINS_TO_EXCLUDE = "domainsToExclude";
  @SerializedName(SERIALIZED_NAME_DOMAINS_TO_EXCLUDE)
  private List<String> domainsToExclude = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTRACT_IMAGES = "extractImages";
  @SerializedName(SERIALIZED_NAME_EXTRACT_IMAGES)
  private Boolean extractImages;

  public AiproductdataenhancerFillProductDataRequest() {
  }

  public AiproductdataenhancerFillProductDataRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public AiproductdataenhancerFillProductDataRequest languageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
    return this;
  }

  /**
   * Get languageCode
   * @return languageCode
   */
  @javax.annotation.Nullable
  public AiproductdataenhancerLanguageCode getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
  }


  public AiproductdataenhancerFillProductDataRequest productInformation(AiproductdataenhancerProductInformation productInformation) {
    this.productInformation = productInformation;
    return this;
  }

  /**
   * Get productInformation
   * @return productInformation
   */
  @javax.annotation.Nullable
  public AiproductdataenhancerProductInformation getProductInformation() {
    return productInformation;
  }

  public void setProductInformation(AiproductdataenhancerProductInformation productInformation) {
    this.productInformation = productInformation;
  }


  public AiproductdataenhancerFillProductDataRequest productDataToFill(List<AiproductdataenhancerProductDataToFill> productDataToFill) {
    this.productDataToFill = productDataToFill;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addProductDataToFillItem(AiproductdataenhancerProductDataToFill productDataToFillItem) {
    if (this.productDataToFill == null) {
      this.productDataToFill = new ArrayList<>();
    }
    this.productDataToFill.add(productDataToFillItem);
    return this;
  }

  /**
   * Get productDataToFill
   * @return productDataToFill
   */
  @javax.annotation.Nullable
  public List<AiproductdataenhancerProductDataToFill> getProductDataToFill() {
    return productDataToFill;
  }

  public void setProductDataToFill(List<AiproductdataenhancerProductDataToFill> productDataToFill) {
    this.productDataToFill = productDataToFill;
  }


  public AiproductdataenhancerFillProductDataRequest domainsToInclude(List<String> domainsToInclude) {
    this.domainsToInclude = domainsToInclude;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addDomainsToIncludeItem(String domainsToIncludeItem) {
    if (this.domainsToInclude == null) {
      this.domainsToInclude = new ArrayList<>();
    }
    this.domainsToInclude.add(domainsToIncludeItem);
    return this;
  }

  /**
   * Get domainsToInclude
   * @return domainsToInclude
   */
  @javax.annotation.Nullable
  public List<String> getDomainsToInclude() {
    return domainsToInclude;
  }

  public void setDomainsToInclude(List<String> domainsToInclude) {
    this.domainsToInclude = domainsToInclude;
  }


  public AiproductdataenhancerFillProductDataRequest domainsToExclude(List<String> domainsToExclude) {
    this.domainsToExclude = domainsToExclude;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addDomainsToExcludeItem(String domainsToExcludeItem) {
    if (this.domainsToExclude == null) {
      this.domainsToExclude = new ArrayList<>();
    }
    this.domainsToExclude.add(domainsToExcludeItem);
    return this;
  }

  /**
   * Get domainsToExclude
   * @return domainsToExclude
   */
  @javax.annotation.Nullable
  public List<String> getDomainsToExclude() {
    return domainsToExclude;
  }

  public void setDomainsToExclude(List<String> domainsToExclude) {
    this.domainsToExclude = domainsToExclude;
  }


  public AiproductdataenhancerFillProductDataRequest extractImages(Boolean extractImages) {
    this.extractImages = extractImages;
    return this;
  }

  /**
   * Get extractImages
   * @return extractImages
   */
  @javax.annotation.Nullable
  public Boolean getExtractImages() {
    return extractImages;
  }

  public void setExtractImages(Boolean extractImages) {
    this.extractImages = extractImages;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AiproductdataenhancerFillProductDataRequest instance itself
   */
  public AiproductdataenhancerFillProductDataRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiproductdataenhancerFillProductDataRequest aiproductdataenhancerFillProductDataRequest = (AiproductdataenhancerFillProductDataRequest) o;
    return Objects.equals(this.tenantId, aiproductdataenhancerFillProductDataRequest.tenantId) &&
        Objects.equals(this.languageCode, aiproductdataenhancerFillProductDataRequest.languageCode) &&
        Objects.equals(this.productInformation, aiproductdataenhancerFillProductDataRequest.productInformation) &&
        Objects.equals(this.productDataToFill, aiproductdataenhancerFillProductDataRequest.productDataToFill) &&
        Objects.equals(this.domainsToInclude, aiproductdataenhancerFillProductDataRequest.domainsToInclude) &&
        Objects.equals(this.domainsToExclude, aiproductdataenhancerFillProductDataRequest.domainsToExclude) &&
        Objects.equals(this.extractImages, aiproductdataenhancerFillProductDataRequest.extractImages)&&
        Objects.equals(this.additionalProperties, aiproductdataenhancerFillProductDataRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, languageCode, productInformation, productDataToFill, domainsToInclude, domainsToExclude, extractImages, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiproductdataenhancerFillProductDataRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    productInformation: ").append(toIndentedString(productInformation)).append("\n");
    sb.append("    productDataToFill: ").append(toIndentedString(productDataToFill)).append("\n");
    sb.append("    domainsToInclude: ").append(toIndentedString(domainsToInclude)).append("\n");
    sb.append("    domainsToExclude: ").append(toIndentedString(domainsToExclude)).append("\n");
    sb.append("    extractImages: ").append(toIndentedString(extractImages)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("languageCode");
    openapiFields.add("productInformation");
    openapiFields.add("productDataToFill");
    openapiFields.add("domainsToInclude");
    openapiFields.add("domainsToExclude");
    openapiFields.add("extractImages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AiproductdataenhancerFillProductDataRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AiproductdataenhancerFillProductDataRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AiproductdataenhancerFillProductDataRequest is not found in the empty JSON string", AiproductdataenhancerFillProductDataRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      // validate the optional field `languageCode`
      if (jsonObj.get("languageCode") != null && !jsonObj.get("languageCode").isJsonNull()) {
        AiproductdataenhancerLanguageCode.validateJsonElement(jsonObj.get("languageCode"));
      }
      // validate the optional field `productInformation`
      if (jsonObj.get("productInformation") != null && !jsonObj.get("productInformation").isJsonNull()) {
        AiproductdataenhancerProductInformation.validateJsonElement(jsonObj.get("productInformation"));
      }
      if (jsonObj.get("productDataToFill") != null && !jsonObj.get("productDataToFill").isJsonNull()) {
        JsonArray jsonArrayproductDataToFill = jsonObj.getAsJsonArray("productDataToFill");
        if (jsonArrayproductDataToFill != null) {
          // ensure the json data is an array
          if (!jsonObj.get("productDataToFill").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `productDataToFill` to be an array in the JSON string but got `%s`", jsonObj.get("productDataToFill").toString()));
          }

          // validate the optional field `productDataToFill` (array)
          for (int i = 0; i < jsonArrayproductDataToFill.size(); i++) {
            AiproductdataenhancerProductDataToFill.validateJsonElement(jsonArrayproductDataToFill.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("domainsToInclude") != null && !jsonObj.get("domainsToInclude").isJsonNull() && !jsonObj.get("domainsToInclude").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domainsToInclude` to be an array in the JSON string but got `%s`", jsonObj.get("domainsToInclude").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("domainsToExclude") != null && !jsonObj.get("domainsToExclude").isJsonNull() && !jsonObj.get("domainsToExclude").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domainsToExclude` to be an array in the JSON string but got `%s`", jsonObj.get("domainsToExclude").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AiproductdataenhancerFillProductDataRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AiproductdataenhancerFillProductDataRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AiproductdataenhancerFillProductDataRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AiproductdataenhancerFillProductDataRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AiproductdataenhancerFillProductDataRequest>() {
           @Override
           public void write(JsonWriter out, AiproductdataenhancerFillProductDataRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AiproductdataenhancerFillProductDataRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AiproductdataenhancerFillProductDataRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AiproductdataenhancerFillProductDataRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AiproductdataenhancerFillProductDataRequest
   * @throws IOException if the JSON string is invalid with respect to AiproductdataenhancerFillProductDataRequest
   */
  public static AiproductdataenhancerFillProductDataRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AiproductdataenhancerFillProductDataRequest.class);
  }

  /**
   * Convert an instance of AiproductdataenhancerFillProductDataRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

