/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.openapitools.client.model.AiproductdataenhancerProductInformation;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_AiProductDataEnhancer.JSON;

/**
 * AiproductdataenhancerFillProductDataRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-02T15:51:08.212237848Z[Etc/UTC]")
public class AiproductdataenhancerFillProductDataRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_LANGUAGE_CODE = "languageCode";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_CODE)
  private AiproductdataenhancerLanguageCode languageCode = AiproductdataenhancerLanguageCode.UNKNOWN;

  public static final String SERIALIZED_NAME_PRODUCT_INFORMATION = "productInformation";
  @SerializedName(SERIALIZED_NAME_PRODUCT_INFORMATION)
  private AiproductdataenhancerProductInformation productInformation;

  public static final String SERIALIZED_NAME_PRODUCT_DATA_TO_FILL = "productDataToFill";
  @SerializedName(SERIALIZED_NAME_PRODUCT_DATA_TO_FILL)
  private List<String> productDataToFill;

  public static final String SERIALIZED_NAME_DOMAINS_TO_INCLUDE = "domainsToInclude";
  @SerializedName(SERIALIZED_NAME_DOMAINS_TO_INCLUDE)
  private List<String> domainsToInclude;

  public static final String SERIALIZED_NAME_DOMAINS_TO_EXCLUDE = "domainsToExclude";
  @SerializedName(SERIALIZED_NAME_DOMAINS_TO_EXCLUDE)
  private List<String> domainsToExclude;

  public AiproductdataenhancerFillProductDataRequest() {
  }

  public AiproductdataenhancerFillProductDataRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public AiproductdataenhancerFillProductDataRequest languageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
    return this;
  }

   /**
   * Get languageCode
   * @return languageCode
  **/
  @javax.annotation.Nullable
  public AiproductdataenhancerLanguageCode getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
  }


  public AiproductdataenhancerFillProductDataRequest productInformation(AiproductdataenhancerProductInformation productInformation) {
    this.productInformation = productInformation;
    return this;
  }

   /**
   * Get productInformation
   * @return productInformation
  **/
  @javax.annotation.Nullable
  public AiproductdataenhancerProductInformation getProductInformation() {
    return productInformation;
  }

  public void setProductInformation(AiproductdataenhancerProductInformation productInformation) {
    this.productInformation = productInformation;
  }


  public AiproductdataenhancerFillProductDataRequest productDataToFill(List<String> productDataToFill) {
    this.productDataToFill = productDataToFill;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addProductDataToFillItem(String productDataToFillItem) {
    if (this.productDataToFill == null) {
      this.productDataToFill = new ArrayList<>();
    }
    this.productDataToFill.add(productDataToFillItem);
    return this;
  }

   /**
   * Get productDataToFill
   * @return productDataToFill
  **/
  @javax.annotation.Nullable
  public List<String> getProductDataToFill() {
    return productDataToFill;
  }

  public void setProductDataToFill(List<String> productDataToFill) {
    this.productDataToFill = productDataToFill;
  }


  public AiproductdataenhancerFillProductDataRequest domainsToInclude(List<String> domainsToInclude) {
    this.domainsToInclude = domainsToInclude;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addDomainsToIncludeItem(String domainsToIncludeItem) {
    if (this.domainsToInclude == null) {
      this.domainsToInclude = new ArrayList<>();
    }
    this.domainsToInclude.add(domainsToIncludeItem);
    return this;
  }

   /**
   * Get domainsToInclude
   * @return domainsToInclude
  **/
  @javax.annotation.Nullable
  public List<String> getDomainsToInclude() {
    return domainsToInclude;
  }

  public void setDomainsToInclude(List<String> domainsToInclude) {
    this.domainsToInclude = domainsToInclude;
  }


  public AiproductdataenhancerFillProductDataRequest domainsToExclude(List<String> domainsToExclude) {
    this.domainsToExclude = domainsToExclude;
    return this;
  }

  public AiproductdataenhancerFillProductDataRequest addDomainsToExcludeItem(String domainsToExcludeItem) {
    if (this.domainsToExclude == null) {
      this.domainsToExclude = new ArrayList<>();
    }
    this.domainsToExclude.add(domainsToExcludeItem);
    return this;
  }

   /**
   * Get domainsToExclude
   * @return domainsToExclude
  **/
  @javax.annotation.Nullable
  public List<String> getDomainsToExclude() {
    return domainsToExclude;
  }

  public void setDomainsToExclude(List<String> domainsToExclude) {
    this.domainsToExclude = domainsToExclude;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiproductdataenhancerFillProductDataRequest aiproductdataenhancerFillProductDataRequest = (AiproductdataenhancerFillProductDataRequest) o;
    return Objects.equals(this.tenantId, aiproductdataenhancerFillProductDataRequest.tenantId) &&
        Objects.equals(this.languageCode, aiproductdataenhancerFillProductDataRequest.languageCode) &&
        Objects.equals(this.productInformation, aiproductdataenhancerFillProductDataRequest.productInformation) &&
        Objects.equals(this.productDataToFill, aiproductdataenhancerFillProductDataRequest.productDataToFill) &&
        Objects.equals(this.domainsToInclude, aiproductdataenhancerFillProductDataRequest.domainsToInclude) &&
        Objects.equals(this.domainsToExclude, aiproductdataenhancerFillProductDataRequest.domainsToExclude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, languageCode, productInformation, productDataToFill, domainsToInclude, domainsToExclude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiproductdataenhancerFillProductDataRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    productInformation: ").append(toIndentedString(productInformation)).append("\n");
    sb.append("    productDataToFill: ").append(toIndentedString(productDataToFill)).append("\n");
    sb.append("    domainsToInclude: ").append(toIndentedString(domainsToInclude)).append("\n");
    sb.append("    domainsToExclude: ").append(toIndentedString(domainsToExclude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("languageCode");
    openapiFields.add("productInformation");
    openapiFields.add("productDataToFill");
    openapiFields.add("domainsToInclude");
    openapiFields.add("domainsToExclude");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AiproductdataenhancerFillProductDataRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AiproductdataenhancerFillProductDataRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AiproductdataenhancerFillProductDataRequest is not found in the empty JSON string", AiproductdataenhancerFillProductDataRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AiproductdataenhancerFillProductDataRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AiproductdataenhancerFillProductDataRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      // validate the optional field `languageCode`
      if (jsonObj.get("languageCode") != null && !jsonObj.get("languageCode").isJsonNull()) {
        AiproductdataenhancerLanguageCode.validateJsonElement(jsonObj.get("languageCode"));
      }
      // validate the optional field `productInformation`
      if (jsonObj.get("productInformation") != null && !jsonObj.get("productInformation").isJsonNull()) {
        AiproductdataenhancerProductInformation.validateJsonElement(jsonObj.get("productInformation"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("productDataToFill") != null && !jsonObj.get("productDataToFill").isJsonNull() && !jsonObj.get("productDataToFill").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `productDataToFill` to be an array in the JSON string but got `%s`", jsonObj.get("productDataToFill").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("domainsToInclude") != null && !jsonObj.get("domainsToInclude").isJsonNull() && !jsonObj.get("domainsToInclude").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domainsToInclude` to be an array in the JSON string but got `%s`", jsonObj.get("domainsToInclude").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("domainsToExclude") != null && !jsonObj.get("domainsToExclude").isJsonNull() && !jsonObj.get("domainsToExclude").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domainsToExclude` to be an array in the JSON string but got `%s`", jsonObj.get("domainsToExclude").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AiproductdataenhancerFillProductDataRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AiproductdataenhancerFillProductDataRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AiproductdataenhancerFillProductDataRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AiproductdataenhancerFillProductDataRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AiproductdataenhancerFillProductDataRequest>() {
           @Override
           public void write(JsonWriter out, AiproductdataenhancerFillProductDataRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AiproductdataenhancerFillProductDataRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AiproductdataenhancerFillProductDataRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AiproductdataenhancerFillProductDataRequest
  * @throws IOException if the JSON string is invalid with respect to AiproductdataenhancerFillProductDataRequest
  */
  public static AiproductdataenhancerFillProductDataRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AiproductdataenhancerFillProductDataRequest.class);
  }

 /**
  * Convert an instance of AiproductdataenhancerFillProductDataRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

