/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AiproductdataenhancerGenerateProductDataRequestProductInformation;
import org.openapitools.client.model.AiproductdataenhancerLanguageCode;
import org.openapitools.client.model.GenerateProductDataRequestProductDataToGenerate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.AiProductDataEnhancer.JSON;

/**
 * AiproductdataenhancerGenerateProductDataRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-20T14:54:03.495312875Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class AiproductdataenhancerGenerateProductDataRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_LANGUAGE_CODE = "languageCode";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_CODE)
  private AiproductdataenhancerLanguageCode languageCode = AiproductdataenhancerLanguageCode.UNKNOWN;

  public static final String SERIALIZED_NAME_PRODUCT_INFORMATION = "productInformation";
  @SerializedName(SERIALIZED_NAME_PRODUCT_INFORMATION)
  private List<AiproductdataenhancerGenerateProductDataRequestProductInformation> productInformation = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRODUCT_DATA_TO_GENERATE = "productDataToGenerate";
  @SerializedName(SERIALIZED_NAME_PRODUCT_DATA_TO_GENERATE)
  private List<GenerateProductDataRequestProductDataToGenerate> productDataToGenerate = new ArrayList<>();

  public AiproductdataenhancerGenerateProductDataRequest() {
  }

  public AiproductdataenhancerGenerateProductDataRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public AiproductdataenhancerGenerateProductDataRequest languageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
    return this;
  }

  /**
   * Get languageCode
   * @return languageCode
   */
  @javax.annotation.Nullable
  public AiproductdataenhancerLanguageCode getLanguageCode() {
    return languageCode;
  }

  public void setLanguageCode(AiproductdataenhancerLanguageCode languageCode) {
    this.languageCode = languageCode;
  }


  public AiproductdataenhancerGenerateProductDataRequest productInformation(List<AiproductdataenhancerGenerateProductDataRequestProductInformation> productInformation) {
    this.productInformation = productInformation;
    return this;
  }

  public AiproductdataenhancerGenerateProductDataRequest addProductInformationItem(AiproductdataenhancerGenerateProductDataRequestProductInformation productInformationItem) {
    if (this.productInformation == null) {
      this.productInformation = new ArrayList<>();
    }
    this.productInformation.add(productInformationItem);
    return this;
  }

  /**
   * Get productInformation
   * @return productInformation
   */
  @javax.annotation.Nullable
  public List<AiproductdataenhancerGenerateProductDataRequestProductInformation> getProductInformation() {
    return productInformation;
  }

  public void setProductInformation(List<AiproductdataenhancerGenerateProductDataRequestProductInformation> productInformation) {
    this.productInformation = productInformation;
  }


  public AiproductdataenhancerGenerateProductDataRequest productDataToGenerate(List<GenerateProductDataRequestProductDataToGenerate> productDataToGenerate) {
    this.productDataToGenerate = productDataToGenerate;
    return this;
  }

  public AiproductdataenhancerGenerateProductDataRequest addProductDataToGenerateItem(GenerateProductDataRequestProductDataToGenerate productDataToGenerateItem) {
    if (this.productDataToGenerate == null) {
      this.productDataToGenerate = new ArrayList<>();
    }
    this.productDataToGenerate.add(productDataToGenerateItem);
    return this;
  }

  /**
   * Get productDataToGenerate
   * @return productDataToGenerate
   */
  @javax.annotation.Nullable
  public List<GenerateProductDataRequestProductDataToGenerate> getProductDataToGenerate() {
    return productDataToGenerate;
  }

  public void setProductDataToGenerate(List<GenerateProductDataRequestProductDataToGenerate> productDataToGenerate) {
    this.productDataToGenerate = productDataToGenerate;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AiproductdataenhancerGenerateProductDataRequest instance itself
   */
  public AiproductdataenhancerGenerateProductDataRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiproductdataenhancerGenerateProductDataRequest aiproductdataenhancerGenerateProductDataRequest = (AiproductdataenhancerGenerateProductDataRequest) o;
    return Objects.equals(this.tenantId, aiproductdataenhancerGenerateProductDataRequest.tenantId) &&
        Objects.equals(this.languageCode, aiproductdataenhancerGenerateProductDataRequest.languageCode) &&
        Objects.equals(this.productInformation, aiproductdataenhancerGenerateProductDataRequest.productInformation) &&
        Objects.equals(this.productDataToGenerate, aiproductdataenhancerGenerateProductDataRequest.productDataToGenerate)&&
        Objects.equals(this.additionalProperties, aiproductdataenhancerGenerateProductDataRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, languageCode, productInformation, productDataToGenerate, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiproductdataenhancerGenerateProductDataRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    languageCode: ").append(toIndentedString(languageCode)).append("\n");
    sb.append("    productInformation: ").append(toIndentedString(productInformation)).append("\n");
    sb.append("    productDataToGenerate: ").append(toIndentedString(productDataToGenerate)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("languageCode");
    openapiFields.add("productInformation");
    openapiFields.add("productDataToGenerate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AiproductdataenhancerGenerateProductDataRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AiproductdataenhancerGenerateProductDataRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AiproductdataenhancerGenerateProductDataRequest is not found in the empty JSON string", AiproductdataenhancerGenerateProductDataRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      // validate the optional field `languageCode`
      if (jsonObj.get("languageCode") != null && !jsonObj.get("languageCode").isJsonNull()) {
        AiproductdataenhancerLanguageCode.validateJsonElement(jsonObj.get("languageCode"));
      }
      if (jsonObj.get("productInformation") != null && !jsonObj.get("productInformation").isJsonNull()) {
        JsonArray jsonArrayproductInformation = jsonObj.getAsJsonArray("productInformation");
        if (jsonArrayproductInformation != null) {
          // ensure the json data is an array
          if (!jsonObj.get("productInformation").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `productInformation` to be an array in the JSON string but got `%s`", jsonObj.get("productInformation").toString()));
          }

          // validate the optional field `productInformation` (array)
          for (int i = 0; i < jsonArrayproductInformation.size(); i++) {
            AiproductdataenhancerGenerateProductDataRequestProductInformation.validateJsonElement(jsonArrayproductInformation.get(i));
          };
        }
      }
      if (jsonObj.get("productDataToGenerate") != null && !jsonObj.get("productDataToGenerate").isJsonNull()) {
        JsonArray jsonArrayproductDataToGenerate = jsonObj.getAsJsonArray("productDataToGenerate");
        if (jsonArrayproductDataToGenerate != null) {
          // ensure the json data is an array
          if (!jsonObj.get("productDataToGenerate").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `productDataToGenerate` to be an array in the JSON string but got `%s`", jsonObj.get("productDataToGenerate").toString()));
          }

          // validate the optional field `productDataToGenerate` (array)
          for (int i = 0; i < jsonArrayproductDataToGenerate.size(); i++) {
            GenerateProductDataRequestProductDataToGenerate.validateJsonElement(jsonArrayproductDataToGenerate.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AiproductdataenhancerGenerateProductDataRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AiproductdataenhancerGenerateProductDataRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AiproductdataenhancerGenerateProductDataRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AiproductdataenhancerGenerateProductDataRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AiproductdataenhancerGenerateProductDataRequest>() {
           @Override
           public void write(JsonWriter out, AiproductdataenhancerGenerateProductDataRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AiproductdataenhancerGenerateProductDataRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AiproductdataenhancerGenerateProductDataRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AiproductdataenhancerGenerateProductDataRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AiproductdataenhancerGenerateProductDataRequest
   * @throws IOException if the JSON string is invalid with respect to AiproductdataenhancerGenerateProductDataRequest
   */
  public static AiproductdataenhancerGenerateProductDataRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AiproductdataenhancerGenerateProductDataRequest.class);
  }

  /**
   * Convert an instance of AiproductdataenhancerGenerateProductDataRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

