/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets aiproductdataenhancerJobStatus
 */
@JsonAdapter(AiproductdataenhancerJobStatus.Adapter.class)
public enum AiproductdataenhancerJobStatus {
  
  UNKNOWN("JOB_STATUS_UNKNOWN"),
  
  PENDING("JOB_STATUS_PENDING"),
  
  RUNNING("JOB_STATUS_RUNNING"),
  
  COMPLETED("JOB_STATUS_COMPLETED"),
  
  FAILED("JOB_STATUS_FAILED");

  private String value;

  AiproductdataenhancerJobStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AiproductdataenhancerJobStatus fromValue(String value) {
    for (AiproductdataenhancerJobStatus b : AiproductdataenhancerJobStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AiproductdataenhancerJobStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final AiproductdataenhancerJobStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AiproductdataenhancerJobStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AiproductdataenhancerJobStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AiproductdataenhancerJobStatus.fromValue(value);
  }
}

