/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.AiproductdataenhancerTone;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.AiProductDataEnhancer.JSON;

/**
 * GenerateProductDataRequestProductDataToGenerate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-20T14:54:03.495312875Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class GenerateProductDataRequestProductDataToGenerate {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE_SET = "valueSet";
  @SerializedName(SERIALIZED_NAME_VALUE_SET)
  private List<String> valueSet = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_TONE = "tone";
  @SerializedName(SERIALIZED_NAME_TONE)
  private AiproductdataenhancerTone tone;

  public GenerateProductDataRequestProductDataToGenerate() {
  }

  public GenerateProductDataRequestProductDataToGenerate name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public GenerateProductDataRequestProductDataToGenerate valueSet(List<String> valueSet) {
    this.valueSet = valueSet;
    return this;
  }

  public GenerateProductDataRequestProductDataToGenerate addValueSetItem(String valueSetItem) {
    if (this.valueSet == null) {
      this.valueSet = new ArrayList<>();
    }
    this.valueSet.add(valueSetItem);
    return this;
  }

  /**
   * Get valueSet
   * @return valueSet
   */
  @javax.annotation.Nullable
  public List<String> getValueSet() {
    return valueSet;
  }

  public void setValueSet(List<String> valueSet) {
    this.valueSet = valueSet;
  }


  public GenerateProductDataRequestProductDataToGenerate metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public GenerateProductDataRequestProductDataToGenerate putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Metadata is an optional field to provide additional information to the AI like, max length, min length, field description, etc.
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public GenerateProductDataRequestProductDataToGenerate tone(AiproductdataenhancerTone tone) {
    this.tone = tone;
    return this;
  }

  /**
   * Get tone
   * @return tone
   */
  @javax.annotation.Nullable
  public AiproductdataenhancerTone getTone() {
    return tone;
  }

  public void setTone(AiproductdataenhancerTone tone) {
    this.tone = tone;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GenerateProductDataRequestProductDataToGenerate instance itself
   */
  public GenerateProductDataRequestProductDataToGenerate putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateProductDataRequestProductDataToGenerate generateProductDataRequestProductDataToGenerate = (GenerateProductDataRequestProductDataToGenerate) o;
    return Objects.equals(this.name, generateProductDataRequestProductDataToGenerate.name) &&
        Objects.equals(this.valueSet, generateProductDataRequestProductDataToGenerate.valueSet) &&
        Objects.equals(this.metadata, generateProductDataRequestProductDataToGenerate.metadata) &&
        Objects.equals(this.tone, generateProductDataRequestProductDataToGenerate.tone)&&
        Objects.equals(this.additionalProperties, generateProductDataRequestProductDataToGenerate.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, valueSet, metadata, tone, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateProductDataRequestProductDataToGenerate {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    valueSet: ").append(toIndentedString(valueSet)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    tone: ").append(toIndentedString(tone)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("valueSet");
    openapiFields.add("metadata");
    openapiFields.add("tone");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GenerateProductDataRequestProductDataToGenerate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GenerateProductDataRequestProductDataToGenerate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GenerateProductDataRequestProductDataToGenerate is not found in the empty JSON string", GenerateProductDataRequestProductDataToGenerate.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("valueSet") != null && !jsonObj.get("valueSet").isJsonNull() && !jsonObj.get("valueSet").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `valueSet` to be an array in the JSON string but got `%s`", jsonObj.get("valueSet").toString()));
      }
      // validate the optional field `tone`
      if (jsonObj.get("tone") != null && !jsonObj.get("tone").isJsonNull()) {
        AiproductdataenhancerTone.validateJsonElement(jsonObj.get("tone"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GenerateProductDataRequestProductDataToGenerate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GenerateProductDataRequestProductDataToGenerate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GenerateProductDataRequestProductDataToGenerate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GenerateProductDataRequestProductDataToGenerate.class));

       return (TypeAdapter<T>) new TypeAdapter<GenerateProductDataRequestProductDataToGenerate>() {
           @Override
           public void write(JsonWriter out, GenerateProductDataRequestProductDataToGenerate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GenerateProductDataRequestProductDataToGenerate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GenerateProductDataRequestProductDataToGenerate instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GenerateProductDataRequestProductDataToGenerate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GenerateProductDataRequestProductDataToGenerate
   * @throws IOException if the JSON string is invalid with respect to GenerateProductDataRequestProductDataToGenerate
   */
  public static GenerateProductDataRequestProductDataToGenerate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GenerateProductDataRequestProductDataToGenerate.class);
  }

  /**
   * Convert an instance of GenerateProductDataRequestProductDataToGenerate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

