/*
 * aiproductdataenhancer/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import GeminiCommerce_AiProductDataEnhancer.ApiException;
import org.openapitools.client.model.AiproductdataenhancerFillProductDataRequest;
import org.openapitools.client.model.AiproductdataenhancerFillProductDataResponse;
import org.openapitools.client.model.RpcStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AiProductDataEnhancerApi
 */
@Disabled
public class AiProductDataEnhancerApiTest {

    private final AiProductDataEnhancerApi api = new AiProductDataEnhancerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void aiProductDataEnhancerFillProductDataTest() throws ApiException {
        AiproductdataenhancerFillProductDataRequest body = null;
        AiproductdataenhancerFillProductDataResponse response = api.aiProductDataEnhancerFillProductData(body);
        // TODO: test validations
    }

}
